version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    command: sh -c "chmod 600 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    networks:
      - rabbitmq_go_net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=inventory_db

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  postgres:
    driver: local
