apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app-fastapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: api-app

  source:
    repoURL: https://github.com/mau-vargas/inventory
    targetRevision: main
    path: 'k8s/inventory/'

  destination:
    server: https://kubernetes.default.svc
    namespace: api-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
