apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Never
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432

      initContainers:
      - name: init-sql
        image: postgres:14-alpine
        command: 
          - "bash"
          - "-c"
          - |
            psql -U postgres -d postgres -c "CREATE ROLE IF NOT EXISTS admin_user WITH LOGIN PASSWORD 'admin_password'; CREATE DATABASE IF NOT EXISTS inventory_db WITH OWNER admin_user;"
            psql -U postgres -d inventory_db -c "CREATE TABLE IF NOT EXISTS inventory (product_id SERIAL PRIMARY KEY, code INT, name_product VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL, available_quantity INT NOT NULL, unit_price VARCHAR(50) NOT NULL, supplier VARCHAR(50) NOT NULL, entry_date VARCHAR(50) NOT NULL, update_date VARCHAR(50) NOT NULL, detail VARCHAR(255) NOT NULL); INSERT INTO inventory (code, name_product, category, available_quantity, unit_price, supplier, entry_date, update_date, detail) VALUES (1, 'Tornillo Phillips de 3/4 pulgada', 'Materiales de fijación', '500', '10', 'Ferretería González', '10-06-23', '10-06-23', 'Tornillo de cabeza Phillips con rosca de 3/4 de pulgada de longitud.'), (2, 'Martillo de carpintero', 'Herramientas', '150', '120', 'Herramientas López', '11-06-23', '11-06-23', 'Martillo de carpintero con mango de madera y cabeza de acero.'), (3, 'Taladro eléctrico 500W', 'Herramientas eléctricas', '75', '950', 'Eléctricos S.A.', '12-06-23', '12-06-23', 'Taladro eléctrico de 500W con control de velocidad y función de impacto.'), (4, 'Llave inglesa ajustable', 'Herramientas', '200', '80', 'Ferretería Central', '13-06-23', '13-06-23', 'Llave inglesa ajustable de 10 pulgadas con mango antideslizante.'), (5, 'Cinta métrica de 5 metros', 'Medición', '300', '50', 'Mediciones Precisas', '14-06-23', '14-06-23', 'Cinta métrica de 5 metros con carcasa de plástico resistente.'), (6, 'Destornillador plano de 6 pulgadas', 'Herramientas', '250', '20', 'Herramientas López', '15-06-23', '15-06-23', 'Destornillador plano de 6 pulgadas con mango ergonómico.'), (7, 'Caja de clavos de 2 pulgadas', 'Materiales de fijación', '5000', '5', 'Ferretería González', '16-06-23', '16-06-23', 'Caja de clavos de 2 pulgadas para carpintería y construcción.'), (8, 'Sierra circular de 1400W', 'Herramientas eléctricas', '60', '1200', 'Eléctricos S.A.', '17-06-23', '17-06-23', 'Sierra circular de 1400W con disco de corte de 7 pulgadas.'), (9, 'Juego de llaves Allen', 'Herramientas', '180', '100', 'Herramientas López', '18-06-23', '18-06-23', 'Juego de llaves Allen de diversos tamaños en estuche portátil.'),
