apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-fastapi
    argocd.argoproj.io/instance: inventory
    lang: node
    platform: services
  name: inventory-service
  namespace: testing
spec:
  selector:
    app: inventory-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8005
  type: ClusterIP
