name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "ing.mauvargas@gmail.com"
        password: "maufunk1"   
    # - name: Build the Docker image
    #   run: |
    #     cd app/
    #     docker build -t your-dockerhub-username/your-image-name:your-tag .